apiVersion: v1
kind: Pod
metadata:
  name: clientpod
  labels:
    app: client
spec:
  containers:
  - name: nginx
    image: busybox:1.28.4
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
