apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
